export const svgIcons = [
  "brand-twitter",
  "brand-linkedin",
  "brand-facebook",
  "brand-telegram",
  "brand-zalo",
  "outline-clock",
  "chevron-right",
  "chevron-left",
  "chevron-down",
  "chevron-up",
  "close-outline",
  "facebook",
  "google",
  "github",
  "overview",
  "business",
  "leadership",
  "finance",
  "techniques",
  "health",
  "note-stack-outline"
] as const
